### ISSUE TITLE
Let's share your nice position together

### ISSUE THREAD

**Issue by jiemojiemo** [mfron/PokemonGo-Bot#63]
![default](https://cloud.githubusercontent.com/assets/13779459/17284147/af577da6-57ea-11e6-8977-667184f0eba1.PNG)
The default position is great! 
Do you have a better position? Show me.

**Comment by dreite** [comment]
Try this one :)

35.6557852,
139.7580405

**Comment by kingcreek** [comment]
sidney

**Comment by elffish** [comment]
San Francisco  :)

**Comment by Lihouf** [comment]
![image](https://cloud.githubusercontent.com/assets/10142150/17291045/e34eceb0-57e1-11e6-86b2-0f06f2be2920.png)

**Comment by freezea** [comment]
@Lihouf thanks, 237 pokestops :D

**Comment by relapz3** [comment]
GO TO MANHATTAN! 327 POKESTOP and XP IN 144511/hour

**Comment by Lihouf** [comment]
@relapz3 Lat and long?
