### ISSUE TITLE
Can't build successfully in newst code.

### ISSUE THREAD

**Issue by supersupereight** [mfron/PokemonGo-Bot#72]
As title.

**Comment by kingcreek** [comment]
error ?

**Comment by supersupereight** [comment]
![1](https://cloud.githubusercontent.com/assets/20751423/17298362/3d631366-583c-11e6-8432-d89729204a19.PNG)

Yes, I got error.

**Comment by kingcreek** [comment]
you've edited the code/design ?

**Comment by kingcreek** [comment]
private void pokémonToolStripMenuItem_Click(object sender, EventArgs e)
        {
            var pokemonList = new PokemonList();
            pokemonList.Show();
        }

**Comment by supersupereight** [comment]
I change another machine, it seems OK.
I will try to find reason, thank you.

**Comment by kingcreek** [comment]
go to design view (MainForm) and double click in pokemon
![screenshot_1](https://cloud.githubusercontent.com/assets/12265884/17300719/d73b1570-5813-11e6-82f0-ff77d529969b.png)
and paste this: 
var pokemonList = new PokemonList();
pokemonList.Show();

**Comment by Zayceur** [comment]
I just make a push. Try to recompile with the last version !
