### ISSUE TITLE
Hello all ! Read this please :)

### ISSUE THREAD

**Issue by mfron** [mfron/PokemonGo-Bot#73]
![sans titre](https://cloud.githubusercontent.com/assets/11887274/17301263/5e052a08-5816-11e6-9746-52f8a00900d1.png)
As i can see, the bot is running good, but im sorry i cant read all of you for the moment, im working.

I need recruit some guys for work with me on this fastest pokemon go bot.

Read you later, bye :)

**Comment by freezea** [comment]
where is this? :D

**Comment by Zayceur** [comment]
@freezea That is San Francisco.

**Comment by starktony1** [comment]
@freezea Default bot location
