### ISSUE TITLE
transfer in IV mode

### ISSUE THREAD

**Issue by supersupereight** [mfron/PokemonGo-Bot#74]
I set the transfer mode to IV mode.
And some pokemons that I don't set to transfer list.
But it still sent the pokemon that I won't transfer.
Is it a bug now?

**Comment by Zayceur** [comment]
Do you have the latest version ?

**Comment by supersupereight** [comment]
Now, I use latest version on 8/1.
I not yet try latest version on 8/2.

**Comment by Zayceur** [comment]
I made an update. Give a try.
