### ISSUE TITLE
[PROB] Pokemon Inventory Full

### ISSUE THREAD

**Issue by Bagnous** [mfron/PokemonGo-Bot#79]
Hi there,
am i the only one who gets the pokemon inventory full and then not being able to catch, the transfert mode is Duplicate, very strange because on the version 3.0.0 it was working good

**Comment by pamallen** [comment]
Same problem, tested Duplicate IV and reguler IV modes as well, the bot doesn't transfer anything

**Comment by mfron** [comment]
Did you got the last version ? it was patched

**Comment by Bagnous** [comment]
yes i'm on the last version that you commited 2 hours ago, and still not fixed, i cameback using 3.0.0 till it get fixed
THANK YOU ALOT FOR YOUR JOB AND YOUR HARD WORK

**Comment by Zayceur** [comment]
I had the same issue and fix it right now !
Try the last version and tell me if it does always the bug.

**Comment by Bagnous** [comment]
Ok thank you so much, i will try

**Comment by evoamac** [comment]
I found that the Transfer callout sometime hangs, so it stop transfering but doesn't exit out the method, like just sit there and wait for something that's never gonna finish processing. I'm trying to add a timeout of some sort to that transfer method.

**Comment by Bagnous** [comment]
it got fixed, download the new version

**Comment by dreite** [comment]
@Zayceur would you please update the compiled version?
btw, @mfron Thank you so much, this is great bot :+1:
