### ISSUE TITLE
still bug cannot auto Transfer setting IV duplicate and the latest version.

### ISSUE THREAD

**Issue by bl4zevenaar** [mfron/PokemonGo-Bot#88]

**Comment by bl4zevenaar** [comment]
![screenshot_81](https://cloud.githubusercontent.com/assets/20690185/17312684/ab0f0bbc-587e-11e6-9cf1-8576fd4ae2d7.png)

**Comment by mfron** [comment]
Transfert is only when you got more than 230pkms

**Comment by bl4zevenaar** [comment]
okay thx
