### ISSUE TITLE
transfer in IV mode still doesn't work for release version 3.3.2

### ISSUE THREAD

**Issue by supersupereight** [mfron/PokemonGo-Bot#97]
Hi developers.
I still doesn't work successfully transfer in IV with version 3.3.2.

Test steps as below:
1.click pokemon ui and select poekmon that I want to transfer, I only select "Weedle", Pidgey"", "Pidgeotto", "Rattata" and "Raticate".

2.click save button and turn off bot.

3.run bot application and check pokemon settings again, it's OK.

4.start bot , after a while, bot still transfer pokemon that I won't to transfer.

![2](https://cloud.githubusercontent.com/assets/20751423/17315235/ad76daa6-589c-11e6-9f96-e6c16a91b67d.JPG)

![3](https://cloud.githubusercontent.com/assets/20751423/17315237/afc5f8fa-589c-11e6-89bb-5760b63cad92.JPG)

**Comment by mfron** [comment]
:O i will look that now

**Comment by mfron** [comment]
did you saved the conf ?

**Comment by mfron** [comment]
But where you see it dosent work ? he just transfert every pokemon who are behind 80%iv

**Comment by supersupereight** [comment]
Yes, it work, but it should transfer the pokemon that I select, right?
Or I got mistake on this function?

**Comment by supersupereight** [comment]
And I select the transfered pokemon list like below image.

![4](https://cloud.githubusercontent.com/assets/20751423/17315442/1dd08a58-589e-11e6-901e-d53892a0c7d7.JPG)

**Comment by mfron** [comment]
yes, only if his iv is bellow 80

**Comment by jiemojiemo** [comment]
where can I open pokemon list ?
I can't find it
